config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  resources :orders
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cart', to: 'products#add_to_cart', as: 'cart'
  get '/collect', to: 'products#cart', as: 'collect'
  get '/remove', to: 'products#remove_from_cart', as: 'remove'
  get '/trash', to: 'products#destroy', as: 'trash'
  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class= "alert alert-info mt-4">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class= "alert alert-warning mt-4" role="alert">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer" style="background-color: #5C59D4;">
  <div class="container">
    <div class="row footer-con">
      <div class="col-md-3">
        <h1 class="nav-logo">MyStore</h1>
        <p class="footer-cat">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
      <div class="col-md-3">
        <h5 class="footer-title">Category</h5>
        <p class="footer-cat">Living Room</p>
        <p class="footer-cat">Bed Room</p>
        <p class="footer-cat">Bath Room</p>
        <p class="footer-cat">Kitchen</p>
      </div>
      <div class="col-md-3">
        <h5 class="footer-title">Sitemap</h5>
        <p class="footer-cat">Products</p>
        <p class="footer-cat">Services</p>
        <p class="footer-cat">Articles</p>
        <p class="footer-cat">About Us</p>
      </div>
      <div class="col-md-3">
        <h5 class="footer-title">Follow Us</h5>
        <p class="footer-cat">Facebook</p>
        <p class="footer-cat">Instagram</p>
        <p class="footer-cat">TikTok</p>
        <p class="footer-cat">YouTube</p>
      </div>
    </div>
    <hr style="border-color: #fff;">
    <p class="text-center">&copy; <%= Time.current.year %> MyStore App. All rights reserved.</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary top-nav fixed-top">
  <div class="container-fluid">
    <%= link_to "MyStore", root_path, class: "navbar-brand nav-logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 align-items-center nav-items">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", style: "margin-right: 52px;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link", style: "margin-right: 52px;" %>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link disabled-link" style="margin-right: 52px;">Orders</a>
        </li>
        <li class="nav-item">
          <%= link_to collect_path, class: "nav-link cart-link", style: "margin-right: 10px;" do %>
            Cart <i class="fas fa-shopping-cart"></i> <!-- Font Awesome icon for shopping cart -->
          <% end %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/"><%= current_user.username %> </a>
        </li>
        <li class="nav-item">
          <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary nav-link" do %>
            <i class="fas fa-sign-out"></i> <!-- Font Awesome icon for Log out -->
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <i class="fas fa-user-plus"></i> <!-- Font Awesome icon for Sign up -->
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt"></i> <!-- Font Awesome icon for Log in -->
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>