config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  resources :orders
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/cart', to: 'products#add_to_cart', as: 'cart'
  get '/collect', to: 'products#cart', as: 'collect'
  get '/remove', to: 'products#remove_from_cart', as: 'remove'
  get '/trash', to: 'products#destroy', as: 'trash'
  # Defines the root path route ("/")
  root "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
    has_and_belongs_to_many :orders
    attr_accessor :image_url
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  #add to cart
  def add_to_cart
    @product = Product.find(params[:id])
    @cart << @product.id
    redirect_to products_path, notice: 'Product added to cart successfully!'
  end

  def remove_from_cart
    @product = Product.find(params[:id])
    @cart.delete(@product.id)
    redirect_to collect_path, notice: 'Product removed from cart successfully!'
  end

  #view the cart collection
  def cart
    @cart_products = Product.where(id: @cart)
    @missing_product_ids = @cart - @cart_products.pluck(:id)
  end
   

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end
  

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
<div class="image-box">
    <%= image_tag "image1.jpg", class: "product-image" %>
    <br />
  <br />
  <br />
  </div>
  
  <div class="product-dets">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <%= link_to "Back", products_path, class: "btn btn-outline-secondary" %> | 
  <%= link_to "Delete", @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %> | 
  <%= link_to 'Add to Cart', cart_path(id: product.id), method: :get, class: 'btn btn-outline-primary' %>
  <br />
  <br />
</div>
  
</div>

app/views/products/cart.html.erb
<br />
<br />
<br />
<h1>Cart</h1>
<br />
<br />

<% if @cart_products.any? %>
  <% @cart_products.each do |product| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text"><%= product.description %></p>
        <p class="card-text"><%= number_to_currency(product.price) %></p>
        <%= link_to 'Remove from Cart', remove_path(id: product.id), method: :get, class: 'btn btn-danger' %>
      </div>
    </div>
    <br />
  <% end %>
<% else %>
<br />
<br />
<br />
  <h1>Nothing in the cart</h1>
  <br />
  <br />
  <br />
  <br />
<% end %>
<br />
<br />

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<br />
<br />
<br />

<h1>Products</h1>

<div id="products" class="row">
  <% @products.each_with_index do |product, index| %>
    <div class="col-md-4">
      <div class="card">
      <%= link_to product_path(product) do %>
          <%= image_tag "image1.jpg", class: "card-img-top fixed-size" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text"><%= product.description %></p>
          <p class="card-text">Price: <%= number_to_currency(product.price) %></p>
          <%= link_to "Show this product", product, class: "btn btn-primary" %>
          <%= link_to 'Add to Cart', cart_path(id: product.id), method: :get, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <% if (index + 1) % 3 == 0 %>
      <div> <br /></div> <!-- Empty column for spacing -->
    <% end %>
  <% end %>
</div>
<br />
<%= link_to "New product", new_product_path, class: "btn btn-outline-secondary" %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p class="notice" style="color: green;"><%= notice %></p>
<br />
<br />
<br />
<div class="product-details">
  <%= render @product %>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<%
=begin%>
 <div class="actions">
  <%= link_to "Back", products_path, class: "btn btn-outline-secondary" %> | 
  <%= link_to "Delete", @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
  <br />
  <br />
</div> 
<%
=end%>
<br />
<br />
<br />